### ISSUE TITLE
Is it legal to change the "Commercial use" license after forking this repo? 

### ISSUE THREAD

**Issue by zfy0701** [floragunncom/search-guard-enterprise-modules#35]
It seems AWS open source their open distro
https://aws.amazon.com/blogs/aws/new-open-distro-for-elasticsearch/

one of the repo they open sourced is:
https://github.com/opendistro-for-elasticsearch/security-advanced-modules

it's obvious that AWS's repo is a fork of this one, they change the package name and did some minor modification,

e.g. what's the different between
https://github.com/opendistro-for-elasticsearch/security-advanced-modules/blob/master/src/main/java/com/amazon/dlic/auth/ldap2/LDAPConnectionFactoryFactory.java

and 

https://github.com/floragunncom/search-guard-enterprise-modules/blob/master/src/main/java/com/floragunn/dlic/auth/ldap2/LDAPConnectionFactoryFactory.java

however, it seems that this repo has a commercial license, so is that even legal changing license after forking? that will turn my understanding of open source project over completely...

also if you search 'search guard' in that repo, there is zero result

https://github.com/opendistro-for-elasticsearch/security-advanced-modules/search?q=search+guard&unscoped_q=search+guard
![image](https://user-images.githubusercontent.com/1646270/54316052-07874b80-459d-11e9-96eb-6f96efdf3dab.png)

or is that safe guard has been acquired by AWS?

**Comment by zfy0701** [comment]
I was told their license is valid so I'm going to close the issue for now. 

No matter what, it would be nice to hear the official clarification in the future.

**Comment by vetin4ri** [comment]
@zfy0701 What do you mean by "their license is valid"? All code copy-pasted to OpenDistro is now Apache 2.0 and license for this repository is not valid anymore, so it can be used safely?

**Comment by jochenkressin** [comment]
Search Guard and Open Distro for Elasticsearch are separate products, maintained by separate teams and with separate roadmaps and focus. There is no change in the Search Guard licenses.

**Comment by vetin4ri** [comment]
Yes, I understand that the Search Guard is a separate product, but all rights to the source code which was copied to the OpenDistro belong to the authors. Unless there is a specific agreement between Amazon and floragunn that grants right to that code, the original licence still applies. 

If there is an agreement is there any official confirmation that the rights were properly transfered to Amazon and the code has now Apache 2.0 license? 

In addition, how the same code can and cannot be used commercially? If this is dual-license either both licenses apply, or a client can choose one. In this case both licenses cannot be used at the same time, so the whole product "Search Guard" has a commercial license, but the source code of it is currently on Apache 2.0 license and can be freely used free of charge in part or as a complete plugin, if not used as a part of "Search Guard" product, is that correct?

**Comment by morsik** [comment]
There is official statement of floragunn about this: 
https://discuss.opendistrocommunity.dev/t/why-no-attribution-to-searchguard/131/5

The AWS repo is OK.
